### ISSUE TITLE
Reactive Command Doc sample missing curly braces

### ISSUE THREAD

**Issue by tkefauver** [AvaloniaUI/avalonia-docs#123]
Noticed the [Reactive Command markup](https://docs.avaloniaui.net/docs/next/concepts/reactiveui/reactive-command#reactive-command-) is missing curly braces in the axaml sample. 

Should be:
```
<StackPanel Margin="20">
  <TextBlock Margin="0 5" >User Name</TextBlock>
  <TextBox Text="{Binding UserName}"/>
  <Button Margin="0 20" Command="{Binding SubmitCommand}">Submit</Button>
</StackPanel>
```

No biggie, just trying to help :)

**Comment by stevemonaco** [comment]
Fixed by #136 . Can close @maxkatz6
