### ISSUE TITLE
Update to v11

### ISSUE THREAD

**Issue by grokys** [AvaloniaUI/avalonia-docs#13]
List here the places where the docs are out of date:

- https://github.com/AvaloniaUI/avalonia-docs/pull/12/files/1590a705b11d146c33b76e4e26081610331401fa#diff-76675fb01d0eb84021b48a1e55651fe32159fb9c5909ff02ca057626364bca05: `<FluentTheme Mode="Dark"/>`

**Comment by timunie** [comment]
pretty much every control should be revisited. Some are not even there.
