### ISSUE TITLE
Unable to resolve suitable regular or attached property Mode on type Avalonia.Themes.Fluent.

### ISSUE THREAD

**Issue by cyraid** [AvaloniaUI/avalonia-docs#132]
**Describe the bug**
It does not build. I installed nuget "Avalonia.Themes.Fluent"
`<FluentTheme Mode="Light"/>`

**Expected behavior**
Very simple app, should be running. If I remove the xml line from App.axaml, the app will run having no background window or anything.

**Desktop (please complete the following information):**
- OS: Windows 11

**Comment by timunie** [comment]
@thscott are you willing to file a PR to fix that part of the docs? otherwise I'll do once I find some free minute.
