### ISSUE TITLE
Add documentation of `{x:True}` and `{x:False}`

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-docs#139]
`{x:True}` and `{x:False}` markup extensions are supported in XAML compiler, but it's not mentioned anywhere.
https://github.com/AvaloniaUI/Avalonia/issues/12601
https://github.com/kekekeks/XamlX/pull/47

**Comment by maxkatz6** [comment]
`{x:Null}` too, although it's a bit more commonly known.

**Comment by mgnslndh** [comment]
Where is a good location to document the `x:True` and `x:False` markup extensions (and other like them)? I do not think there is *one* place where all markup extensions are documented.

Are any of these locations a good fit?

- A sub page to [Deep Dives](https://github.com/AvaloniaUI/avalonia-docs/tree/main/docs/concepts) called "Markup Extensions"
- A new section called "Markup Extensions" on the page [Avalonia XAML](https://github.com/AvaloniaUI/avalonia-docs/blob/main/docs/basics/user-interface/introduction-to-xaml.md)

**Comment by maxkatz6** [comment]
I think this structure would be the best here:
```
- Deep Dives
- - Markup Extensions
- - - Standard markup extensions (or something like that)
- - - Implementing a custom markup exception (or something like that)
```

And reference this section from the Avalonia XAML page.

**Comment by maxkatz6** [comment]
Note: technically, False, True, Null, and xStatic are not markup extensions, but compiler intrinsics. However, for simplicity, we can use "markup extension" terminology.

There should be a mention of these intrinsics:
- x:Null
- x:Type
- x:Static
- x:False
- x:True

And markup extensions
- Binding / CompiledBinding / ReflectionBinding
- StaticResource
- DynamicResource
- OnPlatform
- OnFormFactor 

With links to complete documentation where it's available (bindings or resources, for example).
