### ISSUE TITLE
Since 11.0 is released, shouldn't SelectableTextBlock be added to the documentation?

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/avalonia-docs#154]
Since 11.0 is released, shouldn't SelectableTextBlock be added to the documentation?

_Originally posted by @MarkBrainfire in https://github.com/AvaloniaUI/Avalonia/issues/7995#issuecomment-1694576961_

**Comment by derekforeman** [comment]
this can be closed per,https://github.com/AvaloniaUI/avalonia-docs/pull/306
