### ISSUE TITLE
SelectableTextBlock documentation missing

### ISSUE THREAD

**Issue by MarkBrainfire** [AvaloniaUI/avalonia-docs#157]
I'm offering to help write some missing documentation -- particularly the SelectableTextBlock.

Is this the correct repository?  It seems like important documentation here, for the TextBlock for example, just goes to blank pages even though the documentation shows up in the final ver 11 documention.

Also I know you have a detailed reference doc here:
https://reference.avaloniaui.net/api/Avalonia.Controls/TextBlock/
Is this generated or maintained by hand?

With a little guidance, I can be helpful getting the documentation up date.

**Comment by maxkatz6** [comment]
Yes, it's a correct repository.

For example with TextBlock, source code is here https://github.com/AvaloniaUI/avalonia-docs/blob/main/docs/reference/controls/detailed-reference/textblock.md
And on the website - https://docs.avaloniaui.net/docs/next/reference/controls/detailed-reference/textblock


> Also I know you have a detailed reference doc here:
https://reference.avaloniaui.net/api/Avalonia.Controls/TextBlock/
Is this generated or maintained by hand?

Yes, it was generated. But isn't maintained as much atm.

**Comment by derekforeman** [comment]
this can be closed per, https://github.com/AvaloniaUI/avalonia-docs/pull/306
