### ISSUE TITLE
Explain special operators for AvaloniaProperty

### ISSUE THREAD

**Issue by mgnslndh** [AvaloniaUI/avalonia-docs#180]
It would be nice if the custom control documentation could explain how/when to use the special binding operators for AvaloniaProperty.

https://github.com/AvaloniaUI/Avalonia/blob/0b41caf4338c5a7045404988a124d691c5847abd/src/Avalonia.Base/AvaloniaProperty.cs#L169
https://github.com/AvaloniaUI/Avalonia/blob/0b41caf4338c5a7045404988a124d691c5847abd/src/Avalonia.Base/AvaloniaProperty.cs#L184

The background to this request is that I came across the following code in the Avalonia source code when trying to create a custom control inspired by the TimePicker. I was confused because I could not understand it.

```
_presenter[!TimePickerPresenter.MinuteIncrementProperty] = this[!MinuteIncrementProperty];
```

**Comment by timunie** [comment]
that's no special binding syntax for custom controls. It's simply how binding in C# can work. See: https://docs.avaloniaui.net/docs/next/guides/data-binding/binding-from-code#setting-a-binding-in-an-object-initializer

**Comment by mgnslndh** [comment]
I see it is already documented. I just could not find it. Thanks!
