### ISSUE TITLE
Document example error

### ISSUE THREAD

**Issue by Coolkeke** [AvaloniaUI/avalonia-docs#188]
There is an issue with the attached attribute document, it needs improvement!
[https://docs.avaloniaui.net/docs/next/guides/custom-controls/how-to-create-attached-properties](url)

**Comment by MrJul** [comment]
Remarks: changing to `AvaloniaObject` isn't sufficient as the full Rx is also needed to get the correct `Subscribe` overload.
Alternatively `AnonymousObserver` can be used directly, I'm not sure what's usually preferred in the docs.

**Comment by Coolkeke** [comment]
Suggestion: The document should be based on the native Avalonia API provided and should not be mixed with other content

**Comment by maxkatz6** [comment]
@MrJul AddHandler/Changed or something like that. There was an alternative to Subscribe method.
