### ISSUE TITLE
Bring 0.10.x Build From Source page to 11.0

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/avalonia-docs#190]
the page Build Avalonia from Source is missing in 11.0. We should add it back. 
Where should this be placed?

**Comment by maxkatz6** [comment]
We previously discussed, that topics related to the avalonia repository only, should stay in the repository. Like here https://github.com/AvaloniaUI/Avalonia/blob/master/Documentation/build.md

**Comment by rabbitism** [comment]
Make sense.
