### ISSUE TITLE
Missing documentation for Window control in Avalonia 11.x docs

### ISSUE THREAD

**Issue by MiKom** [AvaloniaUI/avalonia-docs#209]
Hello,

I noticed that the `Window` control documentation is missing in Avalonia 11.

It's available for 10.x: https://docs.avaloniaui.net/docs/controls/window
But it's gone in 11.x: https://docs.avaloniaui.net/docs/next/reference/controls/ (no `Window` in the menu on the left).

Confirmed by @stevemonaco here:
https://github.com/AvaloniaUI/Avalonia/discussions/13354#discussioncomment-7359351

**Comment by stevemonaco** [comment]
Added by #252 and should be closed @maxkatz6
