### ISSUE TITLE
ScrollViewer does not have ScrollChaining in 0.10.x

### ISSUE THREAD

**Issue by AustinnK** [AvaloniaUI/avalonia-docs#211]
https://docs.avaloniaui.net/docs/controls/scrollviewer#scrollchaining
https://reference.avaloniaui.net/api/Avalonia.Controls/ScrollViewer/#Properties
https://github.com/AvaloniaUI/Avalonia/blob/5ebe956413e58af6377999c1356b2ff599c3ab86/src/Avalonia.Controls/ScrollViewer.cs

**Comment by timunie** [comment]
reference page is broken (it's , we had no time to fix it as we didn't find an easy fix for now. Please look into source code instead for now.
