### ISSUE TITLE
Broken link on the page "Samples & Tutorials"

### ISSUE THREAD

**Issue by denis-komarov** [AvaloniaUI/avalonia-docs#237]
The link `https://docs.avaloniaui.net/docs/next/music-store-app/` on the page `https://docs.avaloniaui.net/docs/next/tutorials` seems to lead nowhere.

**Comment by timunie** [comment]
this is the correct URL. Can you file a PR to fix it? 
https://docs.avaloniaui.net/docs/next/tutorials/music-store-app/

**Comment by MikeCodesDotNET** [comment]
Seems to be fixed.
