### ISSUE TITLE
Markup Extension doc: Default English translation has been replaced with Russian

### ISSUE THREAD

**Issue by webprofusion-chrisc** [AvaloniaUI/avalonia-docs#271]
As per https://github.com/AvaloniaUI/avalonia-docs/commit/b42036516bb8ca9a84336a7f78668e179a5ad9c6

Currently both the sidebar and doc page for https://docs.avaloniaui.net/docs/reference/mark-up-extensions are in Russian on the main site.

**Comment by maxkatz6** [comment]
Thank you for reporting! Fixed.
