### ISSUE TITLE
Mobile Essentials Documentation

### ISSUE THREAD

**Issue by MikeCodesDotNET** [AvaloniaUI/avalonia-docs#303]
We should have some documentation on how to use Mobile Essential libraries.

Specifically, which to use as there is currently Xamarin.Essentials, Avalonia.Essentials and MAUI.Essentials. 

[Heres an example of the need.](https://github.com/AvaloniaUI/Avalonia/discussions/12621#discussioncomment-8016763)

**Comment by timunie** [comment]
👍 We also need a working sample here for the devs to try out. I'm thinking about bluetooth service, what do you think?

**Comment by maxkatz6** [comment]
I have added some documentation on how to use platform APIs:
https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet#conditional-compilation(as

Will also add a cross-link to Avalonia.Maui Hybrid project for anybody, who wants to use Maui.Essentials. That should be enough for now. 

Sample would be an ideal too, yes.
