### ISSUE TITLE
'Test Drive' section is inconsistent

### ISSUE THREAD

**Issue by ablearthy** [AvaloniaUI/avalonia-docs#313]
In [Create and Run a Project](https://docs.avaloniaui.net/docs/get-started/test-drive/create-a-project) subsection creation of project is done [via](https://github.com/AvaloniaUI/avalonia-docs/blob/a554554d82753fdeb111e18d706f73e8f97c6ccd/docs/get-started/test-drive/create-a-project.md?plain=1#L33) `dotnet new avalonia.app -o GetStartedApp`.

However, in the [next](https://docs.avaloniaui.net/docs/get-started/test-drive/main-window) subsection there's a [paragraph](https://github.com/AvaloniaUI/avalonia-docs/blob/a554554d82753fdeb111e18d706f73e8f97c6ccd/docs/get-started/test-drive/main-window.md?plain=1#L45) about `MainView` that doesn't exist in `avalonia.app` template. Should `avalonia.app` be changed to `avalonia.mvvm` in 'Create and Run a Project' subsection?

**Comment by MikeCodesDotNET** [comment]
Yep, you're absolutely right! I'll get that fixed.

**Comment by MikeCodesDotNET** [comment]
Fixed. Thanks for letting us know!
