### ISSUE TITLE
Tooltip delay is milliseconds not microseconds.

### ISSUE THREAD

**Issue by mrj001** [AvaloniaUI/avalonia-docs#315]
In this [location](https://github.com/AvaloniaUI/avalonia-docs/blob/a554554d82753fdeb111e18d706f73e8f97c6ccd/docs/reference/controls/detailed-reference/tooltip.md?plain=1#L16) on the ToolTip page, I believe the word "microseconds" should be "milliseconds".

**Comment by timunie** [comment]
@mrj001 can you file a PR to fix it?

**Comment by mrj001** [comment]
Done PR #316
