### ISSUE TITLE
PseudoClass doc duplicate and wrong

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/avalonia-docs#317]
There are two pieces of docs for PseudoClass
https://docs.avaloniaui.net/docs/concepts/pseudo-classes
https://docs.avaloniaui.net/docs/reference/styles/pseudo-classes

and this sample is not valid
```csharp
public static readonly PseudoClass CustomPseudoClass = PseudoClass.Parse(":custom");

// to enable
PseudoClasses.Set(CustomPseudoClass);

// to disable
PseudoClasses.Remove(CustomPseudoClass);
```

**Comment by maxkatz6** [comment]
"concepts/pseudo-classes" should be removed I would say.

**Comment by MikeCodesDotNET** [comment]
Theres a ton of duplication within the docs. It's going to take a bit of work to go through and merge / fix.
