### ISSUE TITLE
Docs about ItemsPanelTemplate usage

### ISSUE THREAD

**Issue by timunie** [AvaloniaUI/avalonia-docs#326]
@cerobe you could add a page under docs > DeepDrives and describe how to use a custom ItemsPanel For ItemsControl and friends. From the ItemsControl-page please add a link to that docs.

_Originally posted by @timunie in https://github.com/AvaloniaUI/Avalonia/discussions/14296#discussioncomment-8219936_

**Comment by cerobe** [comment]
@timunie If I understand well the task for this Issue are:

- Create a page under docs > DeeDives on custom ItemsPanel. There should be a description, most used properties and an example.
- The controls that use this should have a link to that new page. So far i have identified:  `ItemsControl`, `ItemPresenter`, `TreeView`, `Carousel`,  `Menu`, `MenuFlyoutPresenter`, `ComboBox` `ListBox`. I'm pretty sure this list is not exhaustive or even correct, could you confirm please?
- Remove the duplicate examples (if any) in the basic controls

**Comment by cerobe** [comment]
All right, I have modified my current PR with the scope discussed above. Please have a good look at the PR as there are a few things that I am unsure about.
