### ISSUE TITLE
AOT  Faq

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/avalonia-docs#329]
Add page with common aot issue

**Comment by felixf4xu** [comment]
I tried very hard to find the document about AOT and Trim.

I hope the new document can be easily browsed at https://docs.avaloniaui.net/docs/deployment/

Just as a note for someone interested:

AvaloniaUI seems to support standard `dotnet` AOT properties, like this:
```xml
  </PropertyGroup>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
```

**Comment by maxkatz6** [comment]
> AvaloniaUI seems to support standard dotnet AOT properties, like this:

Yes. Using standard AOT documentation is recommended, as it's always up to date.
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=windows%2Cnet8

**Comment by hiddenblue** [comment]
hi there. If you find some AOT problem association with JSON serialization, considering the source generator.
This docs must be userful for you
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

**Comment by MikeCodesDotNET** [comment]
I've added a very basic guide.
