### ISSUE TITLE
Broken link on website to announce Avalonia porting to VisionOS

### ISSUE THREAD

**Issue by monkeyK1n9** [AvaloniaUI/avalonia-docs#330]
I didn't know where to give this issue, but I assume that here it is okay.

So, in the platform page, when announcing Avalonia for VisionOS, the link is broken
and it leads to a 404/error page. 
| Platform page | Error page |
|-----------------|-------------|
| ![image](https://github.com/AvaloniaUI/avalonia-docs/assets/91855362/c3a7edac-a570-45fe-a2ac-dd62ec1287c6) | ![image](https://github.com/AvaloniaUI/avalonia-docs/assets/91855362/1c09d013-735a-4b43-b8fb-fdcc8718d75c) |

I later found that the correct link to the article is [this](https://avaloniaui.net/Blog/what-does-vision-pro-mean-for-windows-developers).

Please, can you fix that ?

**Comment by timunie** [comment]
@MikeCodesDotNET

**Comment by MikeCodesDotNET** [comment]
Just pushed a fixed. It should be live within 5 minutes.
