### ISSUE TITLE
Error in example defining-events.md

### ISSUE THREAD

**Issue by Donzasto** [AvaloniaUI/avalonia-docs#342]
` 
RoutedEvent.Register<MyCustomSlider, RoutedEventArgs>(nameof(ValueChanged));
`

RoutedEvent.Register() has two or three parameters.

I can fix this for example:

`
RoutedEvent.Register<MyCustomSlider, RoutedEventArgs>(nameof(ValueChanged), RoutingStrategies.Direct);
`

**Comment by timunie** [comment]
good catch. Could you file a PR to fix that?
