### ISSUE TITLE
Readme should include guidance on docs localization

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/avalonia-docs#355]
Most community PRs target only the English documentation. As such, the states of a doc across localized versions tends to diverge. I've noticed the docs creeping that direction. There should be some guidance on what is expected for primary source doc (English) contributors, localization contributors, and the Avalonia team across these three areas:

1. Small corrections: typos or small code fixes to samples
2. New additions: new documents or sections
3. Cross-cutting changes: new Docusaurus features, structural reorganizations of docs, etc

The third case should probably be responsible to updating all locales, but the first two pose some questions as the contributor won't know all locales. I've basically forwarded these changes only when the localized docs are still untranslated, but that might be a waste of time.

Helps mitigate #276 until there exists some notification/tracking system of what's been outdated.

The readme should also mention how to launch localized docs:

```
npm run start -- --locale zh-Hans
npm run start -- --locale ru
```

For the third case, I use the "Compare Directories" diff feature in Rider to manually ensure changes are propagated. Select two folders, global search for "Compare Directories". But as the docs diverge more, there are more diffs to sort through.

![compare-directories](https://github.com/AvaloniaUI/avalonia-docs/assets/1782158/1a576072-025d-4a68-9ed8-d84f12855e38)

**Comment by rabbitism** [comment]
My two cents. PRs should be marked with ru or zh label if it potentially needs update from other language. So we can regularly review and update.

**Comment by maxkatz6** [comment]
@rabbitism just added two new labels for that.
