### ISSUE TITLE
Remove antiquated notes from v11 docs

### ISSUE THREAD

**Issue by stevemonaco** [AvaloniaUI/avalonia-docs#358]
Some pages, such as https://docs.avaloniaui.net/docs/basics/user-interface/introduction-to-xaml#axaml-file-extension, have references to pre-v11 behavior. IMO, historical changes are irrelevant to learners and should be in a migration guide instead.

There are probably few occurrences of this, but I removed one earlier in #357. Mostly looking for a thumbs up so I can search+PR or discussion on where migration / historical details should be present in the v11 docs.

**Comment by thevortexcloud** [comment]
As long as the information is still available on the docs page for the version it applies to, then it makes sense to do this as far as I am concerned.
