### ISSUE TITLE
Find out how to hide "MinVersion" from the side bar

### ISSUE THREAD

**Issue by maxkatz6** [AvaloniaUI/avalonia-docs#390]
https://github.com/AvaloniaUI/avalonia-docs/blob/main/docs/concepts/services/activatable-lifetime.md?plain=1#L5

![image](https://github.com/AvaloniaUI/avalonia-docs/assets/3163374/cb008de6-d71b-464a-abe4-52113848af5c)

**Comment by stevemonaco** [comment]
Try putting the title into the header metadata. eg.

```
---
id: activatable-lifetime
title: Activatable Lifetime
---

# Activatable Lifetime <MinVersion version="11.1" />
```

Normally, `title` will be used as the initial heading, but is overridden when the document section begins with an h1 (`#`). `title` will still have priority for the sidebar.

**Comment by maxkatz6** [comment]
Yes, it worked. Thanks.
