### ISSUE TITLE
StringFormatValueConverter is not mentioned below as stated in the tip

### ISSUE THREAD

**Issue by mgnslndh** [AvaloniaUI/avalonia-docs#406]
`StringFormatValueConverter` is not mentioned below as stated in the tip:

https://github.com/AvaloniaUI/avalonia-docs/blob/c9b3276abd160c1cfe9a68cc3b28baa5b0c03613/docs/basics/data/data-binding/data-binding-syntax.md?plain=1#L165-L168

![image](https://github.com/AvaloniaUI/avalonia-docs/assets/1139118/595ce595-6813-459d-b21b-6f285badfeff)

**Comment by stevemonaco** [comment]
That refers to the "a string formatting converter" in the section below. It's vague, but I didn't see the need to modify either so I kept it as-is. However, the linked page "built-in-data-binding-converters" doesn't list `StringFormatValueConverter` either so some work should be done there. There are a few others missing, like `EnumToBoolConverter`.

![image](https://github.com/AvaloniaUI/avalonia-docs/assets/1782158/9ba0c3de-1486-4350-a502-497b76eeb058)
