### ISSUE TITLE
TabControl.ContentTemplate uses wrong DataContext #2

### ISSUE THREAD

**Issue by SimonORorke** [AvaloniaUI/avalonia-docs#445]
This is a follow on from [closed Issue 13909 TabControl.ContentTemplate uses wrong DataContext](https://github.com/AvaloniaUI/Avalonia/discussions/13909), as I suggest it warrants further discussion. Let me reformulate the problem in a more long-winded way.

Following the instructions in the [How To Bind Tabs](https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-tabs) page of Avalonia's documentation, in `MainWindow.axaml` I bound a `TabControl` to a collection property of `MainWindowViewModel`, like this:
```
<TabControl x:Name="TabControl"
			ItemsSource="{Binding Tabs}"
			SelectedItem="{Binding SelectedTab}">
	<TabControl.ItemTemplate>
		<DataTemplate>
			<TextBlock Text="{Binding Header}" />
		</DataTemplate>
	</TabControl.ItemTemplate>
	<TabControl.ContentTemplate>
		<DataTemplate>
			<ContentControl Content="{Binding ViewModel}" />
		</DataTemplate>
	</TabControl.ContentTemplate>
</TabControl>
```
The problem is apparent when looking at the same XAML in Rider:
![TabControl Binding Error](https://github.com/AvaloniaUI/Avalonia/assets/79874679/a001543d-92ef-4590-ac2c-74150c6b52c1)
`TabControl.ItemTemplate`, which defines the tab header, correctly binds to a property in the repeating item of the collection to which `ItemsSource` is bound. However, `TabControl.ContentTemplate`, which defines the content shown below the tab, incorrectly attempts to bind to a a non-existent property of the `Window`'s view model instead of the required property of the repeating item.

The solution, as I found in [Issue 13909](https://github.com/AvaloniaUI/Avalonia/discussions/13909), is to add a `DataType` to `TabControl.ContentTemplate`'s `DataTemplate`, like this:
```
<TabControl.ContentTemplate>
	<DataTemplate DataType="viewModel:TabItemViewModel">
		<ContentControl Content="{Binding ViewModel}" />
	</DataTemplate>
</TabControl.ContentTemplate>
```

Is the difference between the binding behaviours of `TabControl.ItemTemplate` and `TabControl.ContentTemplate` a bug?  Or is it as expected?

If it's not a bug, or perhaps till any bug has been fixed, the  [How To Bind Tabs](https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-tabs) documentation needs to be corrected.

**Comment by SimonORorke** [comment]
Thanks for the explanation.  What is a PR?  Is it something you would like me to do to request the documentation fix?

**Comment by timunie** [comment]
PR = "Pull Request". Our docs are written in MarkDown and everyone can file a fix. 

![image](https://github.com/AvaloniaUI/avalonia-docs/assets/47110241/4e102aa2-ba3f-4d10-84b5-9aaa62b2b1ba)

**Comment by SimonORorke** [comment]
OK, I'm happy to do it, but don't want to mess up, as it's my first time. Let's see if I've understood the procedure.  I can see I could edit in place. But it is not obvious to me that that's what I should do.  Do I need to create a branch with the edit for someone to approve?

**Comment by SimonORorke** [comment]
Got it. I’ll give it a go in a few hours, it’s 2:15am here in New Zealand.

**Comment by SimonORorke** [comment]
I have submitted the [pull request](https://github.com/AvaloniaUI/avalonia-docs/pull/446).

**Comment by SimonORorke** [comment]
I have submitted the [pull request](https://github.com/AvaloniaUI/avalonia-docs/pull/446).
