### ISSUE TITLE
XAML Using Prefix can reference a namespace in another assembly

### ISSUE THREAD

**Issue by SimonORorke** [AvaloniaUI/avalonia-docs#460]
According to the **XML Namespaces** section of the [Avalonia XAML](https://docs.avaloniaui.net/docs/basics/user-interface/introduction-to-xaml) page, 

> There is an alternative prefix using: that you can use to reference code in the current assembly.

When researching the pros and cons of the `using:` vs `clr-namespace:` prefixes for providing aliases for namespaces, I found the 2020 feature request for the `using:` syntax.  In his proposal, @maxkatz6 wrote:

> Currently Avalonia supports WPF'style namespaces in XAML files, using clr-namespace with assembly.
> With that we need to provide long path to assemblies, if namespace isn't contained in current one.
> UWP and XF supports another syntax, using "using:" keyword (for UWP it is only one available syntax).
> _With this we don't need to provide assembly, instead it will internally search for namespace in referenced projects and packages._

(My emphasis.) I happen to be working on an application where the view model is in a separate assembly from the UI, so I have checked to see whether, unlike  `clr-namespace:`, `using:` can actually provide an alias for a namespace in another assembly without specifying the assembly path.  It works.

So the documentation does not explain the full power of the `using:` prefix.  Something like this would be better:

> There is an alternative prefix `using:` that you can use to reference a namespace. When the namespace is not in the current assembly, the path of the assembly is not specified. Instead, the namespace is searched for in referenced projects and packages.

**Comment by maxkatz6** [comment]
You are right, documentation isn't correct here. Also, "using:" probably should be moved up and described before "clr-namespace", as we want to keep it as a preferred approach.

**Comment by SimonORorke** [comment]
I agree.  I shall have a go at fixing it up and submit a pull request.
