### ISSUE TITLE
Localizing using ResX should indicate that PublicResXFileCodeGenerator is to be used for Xaml support

### ISSUE THREAD

**Issue by odalet** [AvaloniaUI/avalonia-docs#474]
In <https://docs.avaloniaui.net/docs/guides/implementation-guides/localizing>, creating resx files and making sure their Build Action is `Embedded Resource` is not sufficient for it to work in Xaml.

One should also make sure the Custom Tool is set to `PublicResXFileCodeGenerator` and not the default `ResXFileCodeGenerator`. The latter gererates `internal` code that is not detected by the xaml compiler.

**Comment by timunie** [comment]
@odalet please file a PR to fix that. Thx.

**Comment by odalet** [comment]
See #476
