### ISSUE TITLE
Rewrite Binding to Commands documentation 

### ISSUE THREAD

**Issue by MikeCodesDotNET** [AvaloniaUI/avalonia-docs#507]
The problem doc is [Binding to Commands](https://docs.avaloniaui.net/docs/0.10.x/data-binding/binding-to-commands). 

As per [this question](https://github.com/AvaloniaUI/Avalonia/discussions/15963#discussion-6798768), we default to ReactiveUI, which while very powerful, is incredibly complex for beginners. It might be useful to rewrite this using Community Toolkit? 

In fact, as a larger scope of work, I'd like to see all RxUI references removed from the basic docs and standardise on the community toolkit.

**Comment by stevemonaco** [comment]
These are the 0.10.x docs. Maybe there's a need for a separate colored indicator / warning for 0.10.x doc pages besides the version indicator that blends in.

The v11 docs are a bit different with [ReactiveUI](https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-to-a-command-with-reactiveui) and [method binding](https://docs.avaloniaui.net/docs/guides/data-binding/how-to-bind-to-a-command-without-reactiveui) docs.

Maybe merge these two docs into a single doc and use Tabs to show code for each approach: Mvvm Toolkit, ReactiveUI (if kept), and methods.

**Comment by MikeCodesDotNET** [comment]
Great catch! I didn't even notice! 🙈

I think @kekekeks has discussed potentially removing the 0.10 documentation, as most of our users (>95%) are building with 11.x.
