### ISSUE TITLE
Please setup multi language support for doc site

### ISSUE THREAD

**Issue by rabbitism** [AvaloniaUI/avalonia-docs#53]
So I can start to add Chinese docs.

**Comment by MikeCodesDotNET** [comment]
We can now support multiple languages. If someone wants to submit a PR then I'll be happy to merge. 

https://docusaurus.io/docs/i18n/tutorial

**Comment by Dynesshely** [comment]
If there is no objection, I am willing to do multilingual architecture. (Translated by google)

**Comment by timunie** [comment]
automatic translations can give you a good first working basis, but esp. in the technical translations there can be false translations which leads to wrong or unreadable content. So a human knowing both languages needs to correct these translations. Just take MS automatic translated content. In German language they are horrible to read.
