### ISSUE TITLE
WPF/UWP/Avalonia comparison page says WPF doesn't have a ContentControl.

### ISSUE THREAD

**Issue by WillPittenger** [AvaloniaUI/avalonia-docs#536]
[Controls](https://docs.avaloniaui.net/docs/get-started/wpf/comparison-of-avalonia-with-wpf-and-uwp#controls) says WPF doesn't have [System.Windows.Controls.ContentControl](https://learn.microsoft.com/en-us/dotnet/api/system.windows.controls.contentcontrol?view=windowsdesktop-8.0&f1url=%3FappId%3DDev17IDEF1%26l%3DEN-US%26k%3Dk(System.Windows.Controls.ContentControl)%3Bk(VS.XamlEditor)%26rd%3Dtrue#properties).

**Comment by timunie** [comment]
a PR is welcome

**Comment by MikeCodesDotNET** [comment]
Looks to be fixed.
