### ISSUE TITLE
Page/Window Navigation guides are missing

### ISSUE THREAD

**Issue by lizanx** [AvaloniaUI/avalonia-docs#539]
I'm new to desktop development without any previous experiences in WPF/UWP. I've almost read all the docs and tried nearly all examples showed, and I really thank all people who contributed to it.  
But I find that there is no guide on multi-page/multi-window and navigations bewteen them, and really hope someone experienced can add related docs.

**Comment by JustCallMeQuincy** [comment]
I hope these docs get expanded upon, since this is indeed quite a complicated topic without proper existing documentation (for Avalonia specifically).

**Comment by stevemonaco** [comment]
The primary issue with covering navigation is that there are many ways to implement it depending on who owns the navigation state (a root or temporary View, a root or temporary ViewModel, a service class, etc), who can trigger navigations, and if there are extra features such as managing animations, caching, route restoration, etc. The expectations are also different on mobile and desktop. Accommodating everything can turn a simple base idea (set a View's child to something else) into something that can be quite complex to use. If you've used UWP's `NavigationView` (or a port of such), you'll know what I mean.

If you could specify some scope of what this topic should cover, it could help a contributor focus on what's actually helpful. Most of the topic is opinionated which isn't the best fit for docs.

**Comment by lizanx** [comment]
> The primary issue with covering navigation is that there are many ways to implement it depending on who owns the navigation state (a root or temporary View, a root or temporary ViewModel, a service class, etc), who can trigger navigations, and if there are extra features such as managing animations, caching, route restoration, etc. The expectations are also different on mobile and desktop. Accommodating everything can turn a simple base idea (set a View's child to something else) into something that can be quite complex to use. If you've used UWP's `NavigationView` (or a port of such), you'll know what I mean.
> 
> If you could specify some scope of what this topic should cover, it could help a contributor focus on what's actually helpful. Most of the topic is opinionated which isn't the best fit for docs.

Thanks for your reply!
I know navigation can be a really complicated topic and understand that it's very hard to elaborate it within a few doc pages.
Below are my interested aspects:
1. How can a Window holds multiple stacked views and navigate among them? In this case the Window should have complete control over its children views, and I'd like to know the best practices on how to manage sub-views and their lifecycles inside the Window. (like in Android an Activity can hold multiple Fragments)
2. How can I manage a simple two-window case? The relation between them, their lifecycles and focuses changes will help a lot.

**Comment by thevortexcloud** [comment]
There is actually a very detailed guide already. However it's for ReactiveUI only.

https://docs.avaloniaui.net/docs/concepts/reactiveui/routing

**Comment by lizanx** [comment]
> There is actually a very detailed guide already. However it's for ReactiveUI only.
> 
> https://docs.avaloniaui.net/docs/concepts/reactiveui/routing

I just found the chapter this morning and finished the demo, thanks for your reply.  
I'll close this issue, but I still genuinely hope that there can be similar explanations for CommunityToolkit, and how the `RoutingState` works behind the scenes.

**Comment by thevortexcloud** [comment]
Making a router is a fairly simple thing. It just exposes some viewmodel that the view binds to and some methods used to changing the view model. If you vaguely know what you are doing, you can make one in a few hours. Here is the core of one I wrote awhile back that uses URL style routing (like a website URL) with history.

```csharp
    protected void GoTo(string route, bool addToHistory) {
            if (!route.StartsWith("/")) {
                route = $"/{route}";
            }

            if (route == this.CurrentRoute) {
                return;
            }

            this.CurrentPage = (T)this._resolver.ResolvePage(this._routes[route]);
            if (addToHistory) {
                this._history.Push(route);
            }

            this.CurrentRoute = route;
        }
```
Whenever `CurrentPage` changes, it fires an event which the main view model uses to refresh the view.

**Comment by thevortexcloud** [comment]
You are welcome. Here is a smidge more of the code if you want to actually do something useful with it:

Sample view model:
```csharp
    [RelativeRoute("First")]
    public class FirstViewModel : ViewModelBase { }
```

Here is the code that auto discovers the routes and registers it to the router:

```csharp
       public void DiscoverRoutesInAssembly(Assembly assembly) {
            foreach (var type in assembly.DefinedTypes.Where(o => !o.IsInterface && o.IsClass)) {
                var attributes = type.GetCustomAttributes().OfType<RelativeRouteAttribute>();
                var attribute = attributes.FirstOrDefault();
                if (attribute != null) {
                    this.AddRoute(type.FullName.Replace(assembly.GetName().Name, string.Empty).Replace(".", "/").Replace(type.Name, attribute.Name), type);
                }
            }
        }
```

I never completely finished this though, so it's fairly rough.
