### ISSUE TITLE
SplitButton and ToggleSplitButton missing

### ISSUE THREAD

**Issue by franciscomartinezappeon** [AvaloniaUI/avalonia-docs#54]
**Describe the bug**
The documentation has entries for [SplitButton](https://docs.avaloniaui.net/docs/controls/buttons/splitbutton) and [ToggleSplitButton](https://docs.avaloniaui.net/docs/controls/buttons/togglesplitbutton), however in the XAML and in C# there's no Avalonia.Controls.SplitButton or ToggleSplitButton classes

**To Reproduce**
1. Create Empty Project
2. Try to add a SplitButton to the layout
3. Compiler complains

**Expected behavior**
The SplitButton should be restored, or the respective documentation removed

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Version 0.10.18

**Additional context**
-

**Comment by DamianSuess** [comment]
Unfortunately, I just got bit by this one too.
Our one code base isn't able to upgrade to v11.x quite yet and was excited to use `SplitButton`... "_nope, not yet skipper._" 😆

**Comment by stevemonaco** [comment]
Fixed by #218
