### ISSUE TITLE
The data in the search engine (Algolia) needs to be updated

### ISSUE THREAD

**Issue by jindongjie** [AvaloniaUI/avalonia-docs#545]
When i search using the updated documant title, i cannot find the relevant page.

**Comment by jindongjie** [comment]
I'm not sure if this is automatically synchronized. My pull request was merged about a week ago, but it seems that the data has not been updated yet.

**Comment by MikeCodesDotNET** [comment]
It should be done automatically every week but has never actually worked. It's a manual process, but the last crawl was the 21st of November, so I'm going to close this for now. Let me know if the changes aren't in the search index as I can rerun it.
