### ISSUE TITLE
The setting up editor docs should get updated

### ISSUE THREAD

**Issue by hiddenblue** [AvaloniaUI/avalonia-docs#573]
https://docs.avaloniaui.net/docs/get-started/set-up-an-editor

the setting up docs is outdated. for example,  the preview plugin for rider has already published for a long time

I wonder Whether we could update the part?  The is important for freshman

May I could add some new introduction into it.

![image](https://github.com/user-attachments/assets/11ed982c-023d-4594-b34d-ecca1eef4d81)

**Comment by thevortexcloud** [comment]
PRs are generally welcome. That said I am also not part of the Avalonia team, so it's really up to them.

**Comment by MikeCodesDotNET** [comment]
Fixed.
