### ISSUE TITLE
Dead link in compiled bindings documentation

### ISSUE THREAD

**Issue by legezam** [AvaloniaUI/avalonia-docs#583]
Hi,

While i was reading the documentation about compiled bindings, i found a dead link in the text for known limitations on the same page. However, there is no known limitations on the page.

Issue is here:
https://github.com/AvaloniaUI/avalonia-docs/blob/main/docs/basics/data/data-binding/compiled-bindings.md

**Comment by timunie** [comment]
I think known limitations was removed but the link not. We have way less limitations recently. 

Feel free to provide a PR to remove the dead link. Thanks 🙏
