### ISSUE TITLE
Dead External Link of `JetBrains Rider 2020.3 release announcement`

### ISSUE THREAD

**Issue by realybin** [AvaloniaUI/avalonia-docs#588]
[JetBrains Rider 2020.3 release announcement](https://www.jetbrains.com/rider/whatsnew/2020-3/#version-2020-3-avalonia-support)
https://github.com/AvaloniaUI/avalonia-docs/blob/16e93852c2c9d35e92f80e5638e0965cb56b66e3/docs/get-started/set-up-an-editor.md?plain=1#L19

You can only view near 3 versions' release note. And version 2020.3 is not accessible.

**Comment by timunie** [comment]
oh didn't knew this. A PR to remove it is welcome in this case.
