### ISSUE TITLE
Missing documentation of Selector ^ (Nesting Selector)

### ISSUE THREAD

**Issue by workgroupengineering** [AvaloniaUI/avalonia-docs#62]

**Comment by stevemonaco** [comment]
These docs are [here](https://docs.avaloniaui.net/docs/basics/user-interface/styling/styles#nested-styles), but not within the [styles ref](https://docs.avaloniaui.net/docs/reference/styles/style-selector-syntax). Might be good enough?

**Comment by workgroupengineering** [comment]
I think there should be at least a reference in the [styles](https://docs.avaloniaui.net/docs/reference/styles/style-selector-syntax).
