### ISSUE TITLE
progressbar doc version tag is wrong

### ISSUE THREAD

**Issue by fredlllll** [AvaloniaUI/avalonia-docs#78]
https://docs.avaloniaui.net/docs/controls/progressbar#customizing-the-progress-text

this page mentions you can customize the progress bar text. the version on the top says 0.10.x , but it seems this feature was added later and is not in a current 0.10.x release? is it planned for a 0.10.x release or will it only be in 11.x?

**Comment by maxkatz6** [comment]
Should be moved only to 11.0 version of the doc, you are right. There is a separated file for that.
